---
- name: Install Dev-Kuber Env
  hosts: 127.0.0.1
  connection: local
  become: true
  roles:
    - { role: docker, tags: docker }
    - { role: minikube, tags: minikube }
    - { role: kubectl, tags: kubectl }
    - { role: helm, tags: helm }
